version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 3
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 3
